//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfStudyRoom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatDetail
    {
        public int Id { get; set; }
        public Nullable<int> SeatId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string State { get; set; }
    
        public virtual Seat Seat { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
