//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfStudyRoom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StuRoom
    {
        public StuRoom()
        {
            this.Seat = new HashSet<Seat>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> SeatNum { get; set; }
        public Nullable<int> Empty_Seat { get; set; }
        public string Addr { get; set; }
        public string IsAir { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual ICollection<Seat> Seat { get; set; }
    }
}
