//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfStudyRoom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.SeatDetail = new HashSet<SeatDetail>();
        }
    
        public int Id { get; set; }
        public string StuNo { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Grade { get; set; }
        public string Dormitory { get; set; }
        public string Image { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
    
        public virtual ICollection<SeatDetail> SeatDetail { get; set; }
    }
}
